name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # everyday
defaults:
  run:
    shell: bash
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: install tip
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          if [[ ${{ matrix.os }} == windows* ]]; then
            ./make.bat
          else
            ./make.bash
          fi
          echo "GOROOT=$HOME/gotip" >> "$GITHUB_ENV"
          echo "$HOME/gotip/bin" >> "$GITHUB_PATH"
      - name: go test
        run: |
          go version
          go env
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
