name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # everyday
defaults:
  run:
    shell: bash
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
          rm go.sum
          go clean -modcache
          go mod tidy
          golangci-lint run -v ./...
      - name: install tip
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          if [[ ${{ matrix.os }} == windows* ]]; then
            ./make.bat
          else
            ./make.bash
          fi
          echo "GOROOT=$HOME/gotip" >> "$GITHUB_ENV"
          echo "$HOME/gotip/bin" >> "$GITHUB_PATH"
      - name: go test
        run: |
          go version
          go env
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
